japanese:
  cv:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\dataset\japanese\cv'
  vcv:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\dataset\japanese\vcv'
  cvvc:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\dataset\japanese\cvvc'

korean:
  cv:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\dataset\korean\cv'
  cvc:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\dataset\korean\cvc'
  cvvc:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\dataset\korean\cvvc'
  vcv:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\dataset\korean\vcv'

notes:
  recursive_oto_search: true
  recursive_wav_search: true
  strip_pitch_suffix_for_matching: true
  strip_pitch_suffix_examples:
    - '_C4'
    - '_D4'
    - '-A4'
    - ' F4'
    - '_G4'
    - '#'
