japanese:
  vcv:
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\Meary JP VCV 1.0"
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\HARU"
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\Number Bronze・norn"
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\Number Bronze・quasar"
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\PiER -Allegro-"
  cvvc:
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\Dabi_Test"
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\波音リツEve"

korean:
  cvvc:
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\レウィ_KO ver1"
    - "C:\\Users\\oyh57\\SODAsoo1\\VocalSynth\\OpenUtau\\Singer\\Taiga Iwata Korean CVVC soft"
    - "C:\\Users\\oyh57\\SODAsoo1\\Devs\\Colab\\Ex\\Yeonu_KR_CVVC"
  cvc:
    - "C:\\Users\\oyh57\\SODAsoo1\\Devs\\Colab\\Ex\\SoYoon_KR_CVC"
    - "C:\\Users\\oyh57\\SODAsoo1\\Devs\\Colab\\Ex\\Kei Stellaria KO Light"

notes:
  recursive_oto_search: true
  recursive_wav_search: true
  strip_pitch_suffix_for_matching: true
  strip_pitch_suffix_examples:
    - "_C4"
    - "_D4"
    - "-A4"
    - " F4"
