japanese:
  cv:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\Voice_Datas\Jp\CV_and_Rentan'
  vcv:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\Voice_Datas\Jp\VCV'
  cvvc:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\Voice_Datas\Jp\CVVC'

korean:
  cv:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\Voice_Datas\Kr\CV_and_연단음'
  cvc:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\Voice_Datas\Kr\CVC'
  cvvc:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\Voice_Datas\Kr\CVVC'
  vcv:
    - 'C:\Users\oyh57\SODAsoo1\Devs\UTAU_Auto_OTO_v3\Auto_OTO\Voice_Datas\Kr\VCV'

notes:
  recursive_oto_search: true
  recursive_wav_search: true
  strip_pitch_suffix_for_matching: true
  strip_pitch_suffix_examples:
    - '_C4'
    - '_D4'
    - '-A4'
    - ' F4'
    - '_G4?'
    - '?'
    - '?'
    - '#'
