from __future__ import annotations


def run_kr_vcv_row(
    *,
    syllables_info,
    current_w_idx,
    cv_seq_idx,
    forced_w_idx,
    diphthong_cv_consonant_ratio,
    alias,
    file_format,
    real_wav_name,
    final_lines,
    generate_openutau,
    alias_suffix,
    wav_duration_ms,
    timeline_start_ms,
    timeline_end_ms,
    row_mapping_confidence,
    mel_ctx_for_file,
    base_shape,
    ph_intervals,
    kr_post_ctx,
    fname,
    log_fn,
    validate_fn,
    prepare_vcv_syllable_timing_fn,
    apply_post_timing_pipeline_fn,
    extract_vcv_anchor_points_fn,
    apply_anchor_lock_fn,
    finalize_row_fn,
    row_builder_fn,
    log_post_timing_events_fn,
):
    (
        current_w_idx,
        cv_seq_idx,
        offset,
        consonant,
        cutoff,
        pre,
        ovl,
    ) = prepare_vcv_syllable_timing_fn(
        syllables_info,
        current_w_idx,
        cv_seq_idx,
        diphthong_cv_consonant_ratio,
        forced_w_idx=forced_w_idx,
    )
    (
        offset,
        consonant,
        cutoff,
        pre,
        ovl,
        soft_off_shift,
        soft_cut_shift,
        cutoff_reduced,
    ) = apply_post_timing_pipeline_fn(
        offset,
        consonant,
        cutoff,
        pre,
        ovl,
        alias_type="vcv",
        alias_text=alias,
        file_format=file_format,
        mel_ctx_for_file=mel_ctx_for_file,
        base_shape=base_shape,
        ph_intervals=ph_intervals,
        current_w_idx=current_w_idx,
        syllables_info=syllables_info,
        is_vc_plosive_coda=False,
        enable_stabilize=False,
        enable_cutoff_guard=False,
        post_ctx=kr_post_ctx,
    )
    vcv_anchor, vcv_next_onset, vcv_next_vowel = extract_vcv_anchor_points_fn(
        syllables_info,
        current_w_idx,
    )
    if vcv_anchor is not None:
        offset, consonant, cutoff, pre, ovl = apply_anchor_lock_fn(
            fname=fname,
            alias_text=alias,
            format_type=file_format,
            alias_type="vcv",
            offset=offset,
            consonant=consonant,
            cutoff=cutoff,
            pre=pre,
            ovl=ovl,
            timeline_start_ms=timeline_start_ms,
            timeline_end_ms=timeline_end_ms,
            file_duration_ms=wav_duration_ms,
            anchor_abs_ms=vcv_anchor,
            next_onset_abs_ms=vcv_next_onset,
            next_vowel_abs_ms=vcv_next_vowel,
            mapping_confidence=row_mapping_confidence,
        )
    finalize_row_fn(
        final_lines=final_lines,
        row_builder_fn=row_builder_fn,
        real_wav_name=real_wav_name,
        alias=alias,
        offset=offset,
        consonant=consonant,
        cutoff=cutoff,
        pre=pre,
        ovl=ovl,
        generate_openutau=generate_openutau,
        alias_suffix=alias_suffix,
        alias_type="vcv",
        wav_duration_ms=wav_duration_ms,
        validate_fn=validate_fn,
        log_post_timing_events_fn=log_post_timing_events_fn,
        log_fn=log_fn,
        fname=fname,
        soft_off_shift=soft_off_shift,
        soft_cut_shift=soft_cut_shift,
        cutoff_reduced=cutoff_reduced,
    )
    return current_w_idx, cv_seq_idx


__all__ = ["run_kr_vcv_row"]
